spring:
    application:
        name: XiangLv
    datasource:
        url: jdbc:mysql://47.112.151.152:3306/?characterEncoding=utf-8&useSSL=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: aaa123456
    jpa:
        open-in-view: false

server:
    port: 2020

jpa:
    show-sql: true

